apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka
  name: kafka-service
  namespace: kafka
spec:
  ports:
   - targetPort: 9092
     port: 9092
     protocol: TCP
  type: LoadBalancer
  selector:
    app: kafka
