apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      hostname: kafka
      containers:
      - env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          #value: 10.43.40.119:2181
          value: zookeeper-service.kafka.svc.cluster.local:2181
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka-service.kafka.svc.cluster.local
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        name: kafka
        ports:
         - containerPort: 9092
